=== mvcasillas/examenLLMMtercera/ejercicio1/meteoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- árbol de temperatura con límites superior e inferior
     tipo común a tmax y tmin -->
<xs:simpleType name="temperatura">
    <xs:restriction base="xs:integer">
        <xs:minExclusive value="-100"/>
        <xs:maxExclusive value="100"/>
    </xs:restriction>
</xs:simpleType>

<!-- árbol de predicción con limitaciones de ocurrencias
     los casos con minOccurs=1 hacen que sean obligatorios (mínimo 1)
     y sólo puedan ponerse 1 vez al no tener maxOccurs (el mín es 1 y el máx también)
    
     aviso es opcional así que min 0 máximo 10-->
<xs:complexType name="prediccion">
    <xs:sequence>
        <xs:element name="fecha" minOccurs="1">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{2}\-[0-9]{2}\-[0-9]{4}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="temperaturaMax" type="temperatura" minOccurs="1"/>
        <xs:element name="temperaturaMin" type="temperatura" minOccurs="1"/>
        <xs:element name="probLluvia" minOccurs="1">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{1,3}%"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="aviso" minOccurs="0" maxOccurs="10">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="viento|nieve|tormentas|huracán"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<!-- árbol del simpletype nombre común a CAM, provincia y población
     con validación de patrón-->
<xs:simpleType name="nombre">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z][a-z]+(\s[A-Za-z]+)*"/>
    </xs:restriction>
</xs:simpleType>

<!-- árbol de población para no alargar más el árbol general
     restricción de mínimo 1 predicción, sin límite superior-->
<xs:complexType name="poblacion">
    <xs:sequence>
        <xs:element name="nombre" type="nombre" minOccurs="1"/>
        <xs:element name="prediccion" type="prediccion" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!-- árbol de estructura general con restricciones de número de ocurrencias para cada campo 
     los nombres tienen mínimo 1 occur (son obligatorios) y sin maxOccur = máximo 1 occur-->
<xs:element name="meteorologia">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="comunidadAutonoma" minOccurs="0" maxOccurs="30">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="nombre" minOccurs="1"/>
                        <xs:element name="provincia" minOccurs="0" maxOccurs="20">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="nombre" minOccurs="1"/>
                                    <xs:element name="poblacion" type="poblacion" minOccurs="1" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== mvcasillas/examenLLMMtercera/ejercicio1/meteorologia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE meteorologia>

<meteorologia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="meteoSchema.xsd">

    <comunidadAutonoma>
        <nombre>Comunidad de Madrid</nombre>
        <provincia>
            <nombre>Madrid</nombre>
            <poblacion>
                <nombre>Ciudad Lineal</nombre>
                <prediccion>
                    <fecha>10-02-2000</fecha>
                    <temperaturaMax>20</temperaturaMax>
                    <temperaturaMin>-10</temperaturaMin>
                    <probLluvia>55%</probLluvia>
                    <aviso>viento</aviso>
                    <aviso>nieve</aviso>
                </prediccion>

                <prediccion>
                    <fecha>11-02-2000</fecha>
                    <temperaturaMax>15</temperaturaMax>
                    <temperaturaMin>4</temperaturaMin>
                    <probLluvia>25%</probLluvia>
                </prediccion>
            </poblacion>
            <poblacion>
                <nombre>Alcobendas</nombre>
                <prediccion>
                    <fecha>11-02-2000</fecha>
                    <temperaturaMax>15</temperaturaMax>
                    <temperaturaMin>4</temperaturaMin>
                    <probLluvia>30%</probLluvia>
                </prediccion>
                <prediccion>
                    <fecha>15-02-2000</fecha>
                    <temperaturaMax>12</temperaturaMax>
                    <temperaturaMin>2</temperaturaMin>
                    <probLluvia>50%</probLluvia>
                </prediccion>
            </poblacion>
        </provincia>
    </comunidadAutonoma>

    <comunidadAutonoma>
        <nombre>Comunidad Valenciana</nombre>
        <provincia>
            <nombre>Alicante</nombre>
            <poblacion>
                <nombre>Torrevieja</nombre>
                <prediccion>
                    <fecha>10-03-2000</fecha>
                    <temperaturaMax>25</temperaturaMax>
                    <temperaturaMin>12</temperaturaMin>
                    <probLluvia>0%</probLluvia>
                </prediccion>

                <prediccion>
                    <fecha>11-02-2000</fecha>
                    <temperaturaMax>15</temperaturaMax>
                    <temperaturaMin>4</temperaturaMin>
                    <probLluvia>25%</probLluvia>
                    <aviso>viento</aviso>
                </prediccion>
            </poblacion>

            <poblacion>
                <nombre>Las Matas</nombre>
                <prediccion>
                    <fecha>10-03-2000</fecha>
                    <temperaturaMax>25</temperaturaMax>
                    <temperaturaMin>12</temperaturaMin>
                    <probLluvia>0%</probLluvia>
                </prediccion>
            </poblacion>
        </provincia>

        <provincia>
            <nombre>Valencia</nombre>
            <poblacion>
                <nombre>Valencia</nombre>
                <prediccion>
                    <fecha>10-03-2000</fecha>
                    <temperaturaMax>25</temperaturaMax>
                    <temperaturaMin>12</temperaturaMin>
                    <probLluvia>5%</probLluvia>
                </prediccion>
            </poblacion>
        </provincia>
    </comunidadAutonoma>

</meteorologia>
